### ISSUE TITLE
PM-10k - Dataset

### ISSUE THREAD

**Issue by SamHSlva** [JizhiziLi/GFM#28]
Thank you for sharing your work with the community, it is very interesting. I've just finished reading your paper, and I think your ideas and the PM-10k dataset could help in a project I am working on. Where can I find download instructions for the PM-10k?

**Comment by JizhiziLi** [comment]
Hi there,

Thanks for showing interest in our project.  Since there are some privacy issues in the PM-10, it will be published after privacy-preserving from our new project Privacy-Preserving Portrait Matting very soon. You can check out the Github repo (https://github.com/JizhiziLi/P3M) for updates. In the meantime, you are welcome to try out AM-2k, and BG-20k first. Cheers.
